# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master


pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "15.x"
    displayName: "Install Node.js"

  - script: |
      ls
      npm install
      npm run build
      ls
      popd
    displayName: "Build frontend"
    workingDirectory: 'frontend'

  - script: |
      ls
    workingDirectory: frontend
  - task: AzureFileCopy@4
    inputs:
      SourcePath: 'frontend/build'
      azureSubscription: 'Visual Studio Enterprise Subscription – MPN(0249c9fe-9eb6-46ca-9019-eb9d22c21d71)'
      Destination: 'AzureBlob'
      storage: 'yadejomoviesapp'
      ContainerName: 'frontend'
    
