trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: cd backend
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'