trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*.tests.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    workingDirectory: 'backend'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: 'backend'
    zipAfterPublish: true
- task: AzureRmWebAppDeployment@4
  displayName: Deploy to Azure
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(0249c9fe-9eb6-46ca-9019-eb9d22c21d71)'
    appType: 'webAppLinux'
    WebAppName: 'yadejo-movies-api'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'